import styles from "./page.module.css";
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={styles.body}>
        
        <h1> Sei lá </h1>
        
        {children}</body>
    </html>
  )
}
